spring:
  data:
    mongodb:
      username: spring_student
      password: spring_student
      host: localhost
      port: 27017
      database: customer
      authentication-database: admin
server:
  port: 8090
